version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/activity-frontend
      dockerfile: Dockerfile
    image: activity-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    image: demo-backend:latest
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/GN
    networks:
      - app-network

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
