services:
  frontend:
    build:
      context: ./activity-frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/GN
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
